# Generated by Django 6.0.3 on 2026-03-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('tickets', '0003_ticket_escalated_ticket_escalated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tickets.designation'),
        ),
    ]
