# Generated by Django 6.0.3 on 2026-03-23 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRemovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('reactivated', models.BooleanField(default=False)),
                ('reactivated_at', models.DateTimeField(blank=True, null=True)),
                ('removed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removals_done', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-removed_at'],
            },
        ),
    ]
