# Generated by Django 6.0.3 on 2026-03-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_number', models.CharField(help_text='e.g. A-101, GF-12', max_length=50)),
                ('shop_name', models.CharField(max_length=200)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='tickets.mall')),
            ],
            options={
                'ordering': ['shop_number'],
                'unique_together': {('mall', 'shop_number')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.shop'),
        ),
        migrations.CreateModel(
            name='ShopContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='tenant', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tickets.shop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
