# Generated by Django 6.0.3 on 2026-03-23 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_shop_ticket_shop_shopcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_order', models.PositiveIntegerField(default=1, help_text='1=lowest (Technician), higher number = senior. Escalation goes to next higher level.')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank for all departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='tickets.department')),
            ],
            options={
                'ordering': ['level_order', 'name'],
            },
        ),
    ]
